import { useEffect, useRef, useState, type ReactNode } from "react";
import type { AudioSettings } from "../audio/settings";
import { WebAudioMetronomeEngine } from "../audio/metronome";
import { PianoSynthEngine } from "../audio/pianoSynth";
import type { CapturedMidiMessage } from "../hooks/useMidiInput";
import { foundationPieceResult, type TimedFoundationEvent } from "../learning/foundationPiece";
import { RHYTHM_GRACE_MS, type RhythmStrike } from "../learning/foundationRhythm";
import { midiNoteToName } from "../music/note";

const EVENTS: TimedFoundationEvent[] = [
  { midiNotes:[60],beats:1,onset:0 },{ midiNotes:[62],beats:1,onset:1000 },{ midiNotes:[64],beats:2,onset:2000 },
  { midiNotes:[48],beats:1,onset:4000 },{ midiNotes:[50],beats:1,onset:5000 },{ midiNotes:[52],beats:2,onset:6000 },
  { midiNotes:[61],beats:1,onset:8000 },{ midiNotes:[62],beats:1,onset:9000 },{ midiNotes:[64],beats:2,onset:10000 },
  { midiNotes:[48,60],beats:2,onset:12000 },
];
const RESTS=[{onset:14000,beats:2}];
const ITEMS=[...EVENTS.map((event,index)=>({kind:"note" as const,index,onset:event.onset,beats:event.beats,x:85+event.onset/1000*36})),{kind:"rest" as const,index:0,onset:14000,beats:2,x:612}];
const DURATION=16000; const clockNow=()=>performance.now();
type Phase="idle"|"preparing"|"armed"|"running"|"result"; interface Run{start:number;demo:boolean;strikes:RhythmStrike[]}
interface Props{events:CapturedMidiMessage[];connected:boolean;heldNotes:number[];audioSettings?:AudioSettings;keyboard:(targets:number[],held:number[])=>ReactNode;onFinish:()=>void;onComplete?:()=>void;onConnect?:()=>void}
const staffSteps=[0,0,1,1,2,3,3,4,4,5,5,6];
function trebleY(midi:number){const octave=Math.floor(midi/12)-1;return Math.max(17,Math.min(118,101-(octave*7+staffSteps[((midi%12)+12)%12]-28)*6))-11;}
function bassY(midi:number){const octave=Math.floor(midi/12)-1;return Math.max(17,Math.min(118,71-(octave*7+staffSteps[((midi%12)+12)%12]-21)*6))+75;}
function scoreY(midi:number){return midi>=60?trebleY(midi):bassY(midi);}

export function FoundationPieceLesson({events,connected,heldNotes,audioSettings,keyboard,onFinish,onComplete,onConnect}:Props){
  const[phase,setPhase]=useState<Phase>("idle");const[elapsed,setElapsed]=useState(0);const[notice,setNotice]=useState("");const[result,setResult]=useState<ReturnType<typeof foundationPieceResult>>();const[demonstrating,setDemonstrating]=useState(false);
  const[synth]=useState(()=>new PianoSynthEngine());const[metronome]=useState(()=>new WebAudioMetronomeEngine());const run=useRef<Run|undefined>(undefined);const lastMessage=useRef(events.at(-1)?.id??0);const generation=useRef(0);const active=phase==="preparing"||phase==="armed"||phase==="running";
  function stop(){generation.current+=1;run.current=undefined;synth.stopAll();metronome.stopAll();setPhase("idle");setElapsed(0);}
  function schedule(start:number,demo:boolean){const delay=start-clockNow();for(let beat=0;beat<16;beat+=1)metronome.scheduleClick(`piece:${beat}`,Math.max(0,delay+beat*1000),beat%4===0);if(demo)EVENTS.forEach((event,index)=>event.midiNotes.forEach(midi=>synth.scheduleNote(`piece:${index}:${midi}`,midi,delay+event.onset,event.beats*1000-80)));}
  async function begin(demo:boolean){stop();setNotice("");setResult(undefined);if(demo&&(audioSettings?.muted||audioSettings?.volume===0)){setNotice("Sound is muted. Unmute piano audio to hear the piece.");return;}if(!demo&&heldNotes.length){setNotice("Release the keys first, then start your practice.");return;}const token=generation.current;setPhase("preparing");try{await metronome.prepare();if(demo)await synth.prepare();}catch{if(token!==generation.current)return;if(demo){setNotice("Audio could not start. Please try again.");setPhase("idle");return;}setNotice("The click could not start. Follow the visible count.");}if(token!==generation.current)return;metronome.setVolume(audioSettings?.metronomeVolume??55);synth.setOutput(audioSettings?.volume??65,audioSettings?.muted??false);setDemonstrating(demo);if(!demo){setPhase("armed");return;}const start=clockNow()+100;run.current={start,demo,strikes:[]};schedule(start,demo);setElapsed(clockNow()-start);setPhase("running");}
  useEffect(()=>{for(const event of events){if(event.id<=lastMessage.current)continue;lastMessage.current=event.id;const message=event.message;if(phase==="armed"&&!run.current&&message.kind==="note-on"){if(message.noteNumber!==60||event.heldNotesBefore.length){setNotice("Release the keys, then begin with the first written middle C.");continue;}const start=event.receivedAtMs;run.current={start,demo:false,strikes:[]};for(let beat=0;beat<16;beat+=1)metronome.scheduleClick(`piece:${beat}`,Math.max(0,start+beat*1000-clockNow()),beat%4===0);setNotice("");setPhase("running");}const current=run.current;if(!current||current.demo)continue;const at=event.receivedAtMs-current.start;if(at< -RHYTHM_GRACE_MS||at>DURATION+RHYTHM_GRACE_MS)continue;if(message.kind==="note-on"&&message.noteNumber!==undefined)current.strikes.push({note:message.noteNumber,at});if(message.kind==="note-off"){const strike=[...current.strikes].reverse().find(item=>item.note===message.noteNumber&&item.releasedAt===undefined);if(strike)strike.releasedAt=at;}}},[events,phase,metronome]);
  useEffect(()=>{if(phase!=="running")return;const timer=window.setInterval(()=>{const current=run.current;if(!current)return;const time=clockNow()-current.start;setElapsed(time);if(time<DURATION+(current.demo?0:RHYTHM_GRACE_MS+50))return;run.current=undefined;metronome.stopAll();synth.stopAll();if(current.demo){setPhase("idle");setElapsed(0);setNotice("Your turn. Read one bar ahead and keep counting through the final rest.");}else{const outcome=foundationPieceResult(EVENTS,RESTS,current.strikes);setResult(outcome);if(outcome.passed)onComplete?.();setPhase("result");setNotice("");}},25);return()=>window.clearInterval(timer);},[phase,metronome,onComplete,synth]);
  useEffect(()=>{synth.setOutput(audioSettings?.volume??65,audioSettings?.muted??false);metronome.setVolume(audioSettings?.metronomeVolume??55);},[audioSettings,synth,metronome]);useEffect(()=>()=>{generation.current+=1;run.current=undefined;synth.close();metronome.close();},[synth,metronome]);useEffect(()=>{if(connected||run.current?.demo)return;generation.current+=1;run.current=undefined;metronome.stopAll();setPhase("idle");},[connected,metronome]);
  const playing=phase==="running"&&elapsed>=0;const found=playing?ITEMS.findIndex(item=>elapsed>=item.onset&&elapsed<item.onset+item.beats*1000):0;const currentIndex=found<0?ITEMS.length-1:found;const current=ITEMS[currentIndex];const currentEvent=current.kind==="note"?EVENTS[current.index]:undefined;const progress=Math.min(1,Math.max(0,(elapsed-current.onset)/(current.beats*1000)));const markerX=playing?current.x+progress*((ITEMS[currentIndex+1]?.x??678)-current.x):undefined;const demoHeld=phase==="running"&&demonstrating&&currentEvent&&elapsed<currentEvent.onset+currentEvent.beats*1000-80?currentEvent.midiNotes:[];const shownHeld=phase==="running"&&demonstrating?demoHeld:heldNotes;const labels={correct:"✓",early:"Early",late:"Late",missed:"Miss"}as const;
  return <div className="rhythm-teacher foundation-piece-teacher"><h3>Play your first complete four-bar piece</h3><p>Keep a steady pulse through both hands, the C sharp, the two-note ending, and the final two-beat rest. Your first middle C starts the piece whenever you are ready.</p><div className="rhythm-teacher-actions"><button className="foundation-demo-button" disabled={active} onClick={()=>void begin(true)}>♫ Hear and watch</button><button disabled={active||!connected} onClick={()=>void begin(false)}>{result?"Try again":"Try with guidance"}</button>{active?<button onClick={stop}>Stop</button>:null}</div>{!connected?<div><p>Connect your MIDI piano to practise. The demonstration is available now.</p><button onClick={onConnect}>Connect MIDI</button></div>:null}<div className="rhythm-count"><strong>{phase==="armed"?"Ready":phase==="preparing"?"Preparing…":playing?elapsed>=DURATION?"Stay silent":`Bar ${Math.floor(elapsed/4000)+1} · Count ${Math.floor(elapsed/1000)%4+1}`:"60 BPM"}</strong><span>{phase==="armed"?"Press the first middle C to begin":playing&&current.kind==="rest"?"Final rest — keep counting and release both keys":currentEvent?.midiNotes.length===2?"Hold both C notes through two complete counts":"Read one note ahead as you play"}</span></div>
    <figure className="foundation-piece-card timed-feedback" role="img" aria-label="Four-bar beginner piece with note-by-note timing and final-rest feedback"><svg viewBox="0 0 720 225" aria-hidden="true">{[30,42,54,66,78,116,128,140,152,164].map(y=><line key={y} x1="34" x2="678" y1={y} y2={y}/>)}{[34,229,373,517,678].map(x=><line key={x} className="barline" x1={x} x2={x} y1="30" y2="164"/>)}<text className="clef" x="40" y="80">𝄞</text><text className="clef bass" x="43" y="157">𝄢</text>
      {EVENTS.map((event,index)=>{const x=85+event.onset/1000*36;return <g key={index} className={playing&&current.kind==="note"&&current.index===index?"active":""}>{event.midiNotes.map(midi=>{const y=scoreY(midi);return <g key={midi}>{midi===60?<line className="ledger" x1={x-15} x2={x+15} y1={y} y2={y}/>:null}{midi===61?<text className="accidental" x={x-19} y={y+7}>♯</text>:null}<ellipse className={`piece-notehead${event.beats===1?" filled":""}`} cx={x} cy={y} rx="8" ry="5.5" transform={`rotate(-18 ${x} ${y})`}/><line className="piece-stem" x1={x+7} x2={x+7} y1={y-1} y2={y-31}/></g>})}{result?.notes[index]?<g className={`rhythm-note-result ${result.notes[index].status}`}><rect x={x-16} y="184" width="32" height="18" rx="9"/><text x={x} y="196">{labels[result.notes[index].status]}</text></g>:null}</g>;})}<g className="rest-symbol"><rect x="602" y="134" width="20" height="6"/></g>{result?.rests[0]?<g className={`rhythm-note-result ${result.rests[0].status}`}><rect x="592" y="184" width="40" height="18" rx="9"/><text x="612" y="196">{result.rests[0].status==="quiet"?"✓ Quiet":"Sound"}</text></g>:null}{[1,2,3,4].map(bar=><text key={bar} className="measure-label" x={121+(bar-1)*154} y="16">Bar {bar}</text>)}{shownHeld.filter(note=>note>=48&&note<=72).slice(0,2).map((note,index)=><g className="played-note-marker" key={`${note}-${index}`}><ellipse cx={(markerX??current.x)+13+index*12} cy={scoreY(note)} rx="8" ry="5.5"/><text x={(markerX??current.x)+13+index*12} y={Math.max(12,scoreY(note)-9)}>{midiNoteToName(note)}</text></g>)}{markerX!==undefined?<line className="demo-marker" x1={markerX} x2={markerX} y1="20" y2="178"/>:null}</svg><figcaption><span><i className="correct"/>✓ On time</span><span>Early / Late / Miss marks the exact event</span><span>Final rest: Quiet or Sound</span></figcaption></figure>
    {keyboard(currentEvent?.midiNotes??[],shownHeld)}<div className="rhythm-teacher-feedback" role="status">{result?<><strong>{result.passed?"You completed the whole piece":"Let’s revisit this piece"}</strong><p>{result.passed?"All four bars kept their written pitches, durations, ending chord, and final silence.":result.issue}</p></>:notice||"The score will review every written event and the final rest. There is no percentage score."}</div>{result?.passed?<div className="foundation-complete-actions lesson-action-dock"><button onClick={()=>void begin(false)}>Practise again</button><button className="primary" onClick={onFinish}>Try sight reading</button></div>:null}</div>;
}
